spring:
  datasource:
    url: jdbc:mysql://db-address:3306/test # URL подключения к БД
    username: test # имя пользователя
    password: test # пароль
  sql:
    init:
      mode: always # для инициализации схемы с использованием schema.sql