spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/shop-realm

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health