spring:
  security:
    oauth2:
      client:
        registration:
          storefront:                # registrationId
            provider: keycloak      # ссылка на блок provider
            client-id: storefront-client
            client-secret: ${STORE_FRONT_CLIENT_SECRET} # FGIopMQW0f9Vd5ZnQRJqYvJYbSGvimen
            authorization-grant-type: authorization_code
            scope: openid,profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/shop-realm

  application:
    name: re-shop

  data:
    redis:
      host: 127.0.0.1
      port: 6379
    cache:
      redis:
        time-to-live: PT5M    # TTL по умолчанию для кешей

  r2dbc:
    url: r2dbc:mysql://localhost:3306/reshop # URL подключения к БД
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  sql:
    init:
      mode: never

server:
  port: 8180
  netty:
    connection-timeout: 30s
