spring:
  application:
    name: re-shop

  data:
    redis:
      host: 127.0.0.1
      port: 6379
    cache:
      redis:
        time-to-live: PT5M    # TTL по умолчанию для кешей

  r2dbc:
    url: r2dbc:mysql://localhost:3306/reshop # URL подключения к БД
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  sql:
    init:
      mode: never

server:
  port: 8080
  netty:
    connection-timeout: 30s

#logging:
#  level:
#    io.asyncer.r2dbc.mysql: DEBUG # в этот раз будем логировать запросы напрямую из r2dbc-драйвера